name: Main Workflow

on:
  workflow_dispatch:

jobs:

      uses: vikree/custom-actions-repo/templates/generic-CI.yaml@main    
       with:
          tags: user/containerRepository:latest
          build-args: CUSTOM_BUILD_ARG=value
      
