name: Application Workflow

on:
  workflow_dispatch:

jobs:
  caller:
    uses: vikrees/custom-actions-repo/.github/workflows/generic-ci.yaml@main
    with:
      tags: my-docker-image:latest
      build-args: ARG1=value1,ARG2=value2
