name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: vikree/custom-actions-repo/templates@main
      with:
       tags: user/containerRepository:latest
       build-args: CUSTOM_BUILD_ARG=value
