name: Application Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Reusable Workflow
      uses: vikrees/custom-actions-repo/templates@main
      with:
          tags: my-docker-image:latest
          Dockerfile: ./Dockerfile
          build-args: ARG1=value1,ARG2=value2
          secrets: inherit
          docker_pat: ${{ secrets.DOCKER_PAT }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
