name: Application Workflow

on:
  workflow_dispatch:

jobs:
  call-action-file:
    uses: vikree/custom-actions-repo/.github/workflows/templates/action.yaml@main
    with:
      tags: my-docker-image:latest
      build-args: ARG1=value1,ARG2=value2
