name: Application Workflow

on:
  workflow_dispatch:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  job1:
    needs: checkout-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Custom Actions Repo
        uses: actions/checkout@v2
        with:
          repository: vikree/application
          path: ${{ github.workspace }}

      - name: Use Reusable Workflow
        uses: ./custom-actions/.github/workflows/generic-ci.yaml
        with:
          tags: my-docker-image:latest
          build-args: ARG1=value1,ARG2=value2
          secrets: inherit
