name: Application Workflow

on:
  workflow_dispatch:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  job1:
    needs: checkout-repo
    uses: vikrees/custom-actions-repo/.github/workflows/generic-ci.yaml@main
    with:
      tags: my-docker-image:latest
      build-args: ARG1=value1,ARG2=value2
    secrets: inherit
